##############################
# Board constants
##############################

SIDES_PLAYERS_COUNT = 6

SCREEN_WIDTH = 1260
SCREEN_HEIGHT = 990

PITCH_UP_BORDER = 227
PITCH_DOWN_BORDER = 945
PITCH_LEFT_BORDER = 96
PITCH_RIGHT_BORDER = 1165
PITCH_WIDTH = PITCH_RIGHT_BORDER - PITCH_LEFT_BORDER
PITCH_HEIGHT = PITCH_DOWN_BORDER - PITCH_UP_BORDER

PENALTY_AREA_UP_BORDER = 380
PENALTY_AREA_DOWN_BORDER = 790
LEFTSIDE_PENALTY_AREA_RIGHT_BORDER = 255
RIGHTSIDE_PENALTY_AREA_LEFT_BORDER = 1005


LEFT_SIDE_COORDINATES = {
    "goalkeeper": (PITCH_LEFT_BORDER + PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 2), 
    "defenders": [
        (PITCH_LEFT_BORDER + 2 * PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 2), 
        (PITCH_LEFT_BORDER + 3 * PITCH_WIDTH // 9, PITCH_UP_BORDER + 1 * PITCH_HEIGHT // 3), 
        (PITCH_LEFT_BORDER + 3 * PITCH_WIDTH // 9, PITCH_UP_BORDER + 2 * PITCH_HEIGHT // 3),
    ],
    "strikers": [
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 4),
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9, PITCH_UP_BORDER + 3 * PITCH_HEIGHT / 4), 
    ]
}
RIGHT_SIDE_COORDINATES = {
    "goalkeeper": (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + 4 * PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 2),
    "defenders": [
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + 3 * PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 2), 
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + 2 * PITCH_WIDTH // 9, PITCH_UP_BORDER + 1 * PITCH_HEIGHT // 3), 
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + 2 * PITCH_WIDTH // 9, PITCH_UP_BORDER + 2 * PITCH_HEIGHT // 3),
    ],
    "strikers": [
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + PITCH_WIDTH // 9, PITCH_UP_BORDER + PITCH_HEIGHT // 4), 
        (PITCH_LEFT_BORDER + 4 * PITCH_WIDTH // 9 + PITCH_WIDTH // 9, PITCH_UP_BORDER + 3 * PITCH_HEIGHT // 4),
    ]
}

GOAL_UP_BORDER = 495
GOAL_DOWN_BORDER = 680
GOAL_LEFT_BORDER = 45
GOAL_RIGHT_BORDER = 1220

SCOREBAR_PLACE_RED_SCORE = (570, 120)
SCOREBAR_PLACE_BLUE_SCORE = (680, 120)

##############################
# Game constants
##############################

FPS = 60
FRICTION_A = 60


GOAL_CEREMONY_TIME = 3500 # in miliseconds
WINNER_CEREMONY_TIME = 10000


